name: "TestifySec Action Wrapper"
description: "Downloads and executes another GitHub Action with optional strace instrumentation"
inputs:
  action-ref:
    description: "Reference to the nested action (e.g., owner/repo@ref)"
    required: true
  extra-args:
    description: "Extra arguments to pass to the nested action (deprecated, use input-* instead)"
    required: false
  strace-options:
    description: "Options to pass to strace (default: '-f -v -s 256 -e trace=file,process,network,signal,ipc,desc,memory')"
    required: false
  enable-strace:
    description: "Enable strace instrumentation (default: true)"
    required: false
    default: "true"
  # Any input with the prefix 'input-' will be passed to the nested action
  # For example, input-who-to-greet will be passed as who-to-greet to the nested action
outputs:
  strace-log:
    description: "Path to the strace output log file (if strace was enabled and successful)"
runs:
  using: "node16"
  main: "index.js"
