name: Test Witness Action Wrapper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write  # Required for requesting the JWT
  contents: read   # Required for actions/checkout

jobs:
  test-sigstore-archivista:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci
      
      - name: Test wrapper with time command
        id: time-test
        uses: ./
        with:
          action-ref: "actions/hello-world-javascript-action@main"
          wrapper-command: "time -v"
          input-who-to-greet: "Time"
      
      - name: Check time output
        run: |
          if [ -f "${{ steps.time-test.outputs.wrapper-log }}" ]; then
            echo "Time log file exists at ${{ steps.time-test.outputs.wrapper-log }}"
            cat "${{ steps.time-test.outputs.wrapper-log }}"
          else
            echo "Time log file not found!"
            exit 1
          fi
      
      - name: Upload time logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: time-logs
          path: ${{ steps.time-test.outputs.wrapper-log }}