name: Test Nested Action Wrapper

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Run nested action with wrapper (using time)
        uses: ./
        with:
          action-ref: "actions/hello-world-javascript@v1"
          extra-args: "who-to-greet time"
          wrapper-command: "time"


      - name: Run nested action with wrapper (using time)
        uses: ./
        with:
          action-ref: "actions/hello-world-javascript@v1"
          wrapper-command: "time"
          who-to-greet: "Mona the Octocat"