name: Test Witness Action Wrapper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Test wrapper with basic attestation
        id: attestation
        uses: ./
        with:
          # Action to run
          action-ref: "actions/hello-world-javascript-action@main"
          input-who-to-greet: "World"
          
          # Witness configuration
          step: "hello-world"
          attestations: "command"
          
      - name: Check attestation file
        run: |
          if [[ -f "/tmp/hello-world-attestation.json" ]]; then
            echo "Attestation created successfully"
            jq . "/tmp/hello-world-attestation.json" | head -n 20
          else
            echo "Attestation file not found!"
            exit 1
          fi

  test-multi-attestors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci
      
      - name: Test wrapper with multiple attestors
        id: multi-attestation
        uses: ./
        with:
          # Action to run
          action-ref: "actions/hello-world-javascript-action@main"
          input-who-to-greet: "Witness"
          
          # Witness configuration
          step: "hello-world-multi"
          attestations: "command attestor.git attestor.sbom"
          attestor-sbom-export: "true"
          outfile: "./multi-attestation.json"
      
      - name: Check attestation file
        run: |
          if [[ -f "./multi-attestation.json" ]]; then
            echo "Multi-attestation created successfully"
            jq . "./multi-attestation.json" | head -n 20
          else
            echo "Multi-attestation file not found!"
            exit 1
          fi
      
      - name: Upload attestation as artifact
        uses: actions/upload-artifact@v4
        with:
          name: attestation-files
          path: ./multi-attestation.json